/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteInternetVtcRouteImport } from './routes/site-internet-vtc'
import { Route as SiteInternetRestaurantRouteImport } from './routes/site-internet-restaurant'
import { Route as SiteInternetPmeRouteImport } from './routes/site-internet-pme'
import { Route as SiteInternetPlombierRouteImport } from './routes/site-internet-plombier'
import { Route as SiteInternetPhotovoltaiqueRouteImport } from './routes/site-internet-photovoltaique'
import { Route as SiteInternetIrveRouteImport } from './routes/site-internet-irve'
import { Route as SiteInternetEntrepriseRouteImport } from './routes/site-internet-entreprise'
import { Route as SiteInternetElectricienRouteImport } from './routes/site-internet-electricien'
import { Route as SiteInternetCommerceRouteImport } from './routes/site-internet-commerce'
import { Route as SiteInternetArtisanRouteImport } from './routes/site-internet-artisan'
import { Route as SeoVisibiliteRouteImport } from './routes/seo-visibilite'
import { Route as PubliciteRouteImport } from './routes/publicite'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as InfluencePromotionRouteImport } from './routes/influence-promotion'
import { Route as CrmAutomatisationRouteImport } from './routes/crm-automatisation'
import { Route as CreationDeSiteRouteImport } from './routes/creation-de-site'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const SiteInternetVtcRoute = SiteInternetVtcRouteImport.update({
  id: '/site-internet-vtc',
  path: '/site-internet-vtc',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteInternetRestaurantRoute = SiteInternetRestaurantRouteImport.update({
  id: '/site-internet-restaurant',
  path: '/site-internet-restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteInternetPmeRoute = SiteInternetPmeRouteImport.update({
  id: '/site-internet-pme',
  path: '/site-internet-pme',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteInternetPlombierRoute = SiteInternetPlombierRouteImport.update({
  id: '/site-internet-plombier',
  path: '/site-internet-plombier',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteInternetPhotovoltaiqueRoute =
  SiteInternetPhotovoltaiqueRouteImport.update({
    id: '/site-internet-photovoltaique',
    path: '/site-internet-photovoltaique',
    getParentRoute: () => rootRouteImport,
  } as any)
const SiteInternetIrveRoute = SiteInternetIrveRouteImport.update({
  id: '/site-internet-irve',
  path: '/site-internet-irve',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteInternetEntrepriseRoute = SiteInternetEntrepriseRouteImport.update({
  id: '/site-internet-entreprise',
  path: '/site-internet-entreprise',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteInternetElectricienRoute = SiteInternetElectricienRouteImport.update({
  id: '/site-internet-electricien',
  path: '/site-internet-electricien',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteInternetCommerceRoute = SiteInternetCommerceRouteImport.update({
  id: '/site-internet-commerce',
  path: '/site-internet-commerce',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteInternetArtisanRoute = SiteInternetArtisanRouteImport.update({
  id: '/site-internet-artisan',
  path: '/site-internet-artisan',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoVisibiliteRoute = SeoVisibiliteRouteImport.update({
  id: '/seo-visibilite',
  path: '/seo-visibilite',
  getParentRoute: () => rootRouteImport,
} as any)
const PubliciteRoute = PubliciteRouteImport.update({
  id: '/publicite',
  path: '/publicite',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencePromotionRoute = InfluencePromotionRouteImport.update({
  id: '/influence-promotion',
  path: '/influence-promotion',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmAutomatisationRoute = CrmAutomatisationRouteImport.update({
  id: '/crm-automatisation',
  path: '/crm-automatisation',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationDeSiteRoute = CreationDeSiteRouteImport.update({
  id: '/creation-de-site',
  path: '/creation-de-site',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/creation-de-site': typeof CreationDeSiteRoute
  '/crm-automatisation': typeof CrmAutomatisationRoute
  '/influence-promotion': typeof InfluencePromotionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/publicite': typeof PubliciteRoute
  '/seo-visibilite': typeof SeoVisibiliteRoute
  '/site-internet-artisan': typeof SiteInternetArtisanRoute
  '/site-internet-commerce': typeof SiteInternetCommerceRoute
  '/site-internet-electricien': typeof SiteInternetElectricienRoute
  '/site-internet-entreprise': typeof SiteInternetEntrepriseRoute
  '/site-internet-irve': typeof SiteInternetIrveRoute
  '/site-internet-photovoltaique': typeof SiteInternetPhotovoltaiqueRoute
  '/site-internet-plombier': typeof SiteInternetPlombierRoute
  '/site-internet-pme': typeof SiteInternetPmeRoute
  '/site-internet-restaurant': typeof SiteInternetRestaurantRoute
  '/site-internet-vtc': typeof SiteInternetVtcRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/creation-de-site': typeof CreationDeSiteRoute
  '/crm-automatisation': typeof CrmAutomatisationRoute
  '/influence-promotion': typeof InfluencePromotionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/publicite': typeof PubliciteRoute
  '/seo-visibilite': typeof SeoVisibiliteRoute
  '/site-internet-artisan': typeof SiteInternetArtisanRoute
  '/site-internet-commerce': typeof SiteInternetCommerceRoute
  '/site-internet-electricien': typeof SiteInternetElectricienRoute
  '/site-internet-entreprise': typeof SiteInternetEntrepriseRoute
  '/site-internet-irve': typeof SiteInternetIrveRoute
  '/site-internet-photovoltaique': typeof SiteInternetPhotovoltaiqueRoute
  '/site-internet-plombier': typeof SiteInternetPlombierRoute
  '/site-internet-pme': typeof SiteInternetPmeRoute
  '/site-internet-restaurant': typeof SiteInternetRestaurantRoute
  '/site-internet-vtc': typeof SiteInternetVtcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/creation-de-site': typeof CreationDeSiteRoute
  '/crm-automatisation': typeof CrmAutomatisationRoute
  '/influence-promotion': typeof InfluencePromotionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/publicite': typeof PubliciteRoute
  '/seo-visibilite': typeof SeoVisibiliteRoute
  '/site-internet-artisan': typeof SiteInternetArtisanRoute
  '/site-internet-commerce': typeof SiteInternetCommerceRoute
  '/site-internet-electricien': typeof SiteInternetElectricienRoute
  '/site-internet-entreprise': typeof SiteInternetEntrepriseRoute
  '/site-internet-irve': typeof SiteInternetIrveRoute
  '/site-internet-photovoltaique': typeof SiteInternetPhotovoltaiqueRoute
  '/site-internet-plombier': typeof SiteInternetPlombierRoute
  '/site-internet-pme': typeof SiteInternetPmeRoute
  '/site-internet-restaurant': typeof SiteInternetRestaurantRoute
  '/site-internet-vtc': typeof SiteInternetVtcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/creation-de-site'
    | '/crm-automatisation'
    | '/influence-promotion'
    | '/mentions-legales'
    | '/publicite'
    | '/seo-visibilite'
    | '/site-internet-artisan'
    | '/site-internet-commerce'
    | '/site-internet-electricien'
    | '/site-internet-entreprise'
    | '/site-internet-irve'
    | '/site-internet-photovoltaique'
    | '/site-internet-plombier'
    | '/site-internet-pme'
    | '/site-internet-restaurant'
    | '/site-internet-vtc'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/creation-de-site'
    | '/crm-automatisation'
    | '/influence-promotion'
    | '/mentions-legales'
    | '/publicite'
    | '/seo-visibilite'
    | '/site-internet-artisan'
    | '/site-internet-commerce'
    | '/site-internet-electricien'
    | '/site-internet-entreprise'
    | '/site-internet-irve'
    | '/site-internet-photovoltaique'
    | '/site-internet-plombier'
    | '/site-internet-pme'
    | '/site-internet-restaurant'
    | '/site-internet-vtc'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/creation-de-site'
    | '/crm-automatisation'
    | '/influence-promotion'
    | '/mentions-legales'
    | '/publicite'
    | '/seo-visibilite'
    | '/site-internet-artisan'
    | '/site-internet-commerce'
    | '/site-internet-electricien'
    | '/site-internet-entreprise'
    | '/site-internet-irve'
    | '/site-internet-photovoltaique'
    | '/site-internet-plombier'
    | '/site-internet-pme'
    | '/site-internet-restaurant'
    | '/site-internet-vtc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CreationDeSiteRoute: typeof CreationDeSiteRoute
  CrmAutomatisationRoute: typeof CrmAutomatisationRoute
  InfluencePromotionRoute: typeof InfluencePromotionRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PubliciteRoute: typeof PubliciteRoute
  SeoVisibiliteRoute: typeof SeoVisibiliteRoute
  SiteInternetArtisanRoute: typeof SiteInternetArtisanRoute
  SiteInternetCommerceRoute: typeof SiteInternetCommerceRoute
  SiteInternetElectricienRoute: typeof SiteInternetElectricienRoute
  SiteInternetEntrepriseRoute: typeof SiteInternetEntrepriseRoute
  SiteInternetIrveRoute: typeof SiteInternetIrveRoute
  SiteInternetPhotovoltaiqueRoute: typeof SiteInternetPhotovoltaiqueRoute
  SiteInternetPlombierRoute: typeof SiteInternetPlombierRoute
  SiteInternetPmeRoute: typeof SiteInternetPmeRoute
  SiteInternetRestaurantRoute: typeof SiteInternetRestaurantRoute
  SiteInternetVtcRoute: typeof SiteInternetVtcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/site-internet-vtc': {
      id: '/site-internet-vtc'
      path: '/site-internet-vtc'
      fullPath: '/site-internet-vtc'
      preLoaderRoute: typeof SiteInternetVtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-internet-restaurant': {
      id: '/site-internet-restaurant'
      path: '/site-internet-restaurant'
      fullPath: '/site-internet-restaurant'
      preLoaderRoute: typeof SiteInternetRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-internet-pme': {
      id: '/site-internet-pme'
      path: '/site-internet-pme'
      fullPath: '/site-internet-pme'
      preLoaderRoute: typeof SiteInternetPmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-internet-plombier': {
      id: '/site-internet-plombier'
      path: '/site-internet-plombier'
      fullPath: '/site-internet-plombier'
      preLoaderRoute: typeof SiteInternetPlombierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-internet-photovoltaique': {
      id: '/site-internet-photovoltaique'
      path: '/site-internet-photovoltaique'
      fullPath: '/site-internet-photovoltaique'
      preLoaderRoute: typeof SiteInternetPhotovoltaiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-internet-irve': {
      id: '/site-internet-irve'
      path: '/site-internet-irve'
      fullPath: '/site-internet-irve'
      preLoaderRoute: typeof SiteInternetIrveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-internet-entreprise': {
      id: '/site-internet-entreprise'
      path: '/site-internet-entreprise'
      fullPath: '/site-internet-entreprise'
      preLoaderRoute: typeof SiteInternetEntrepriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-internet-electricien': {
      id: '/site-internet-electricien'
      path: '/site-internet-electricien'
      fullPath: '/site-internet-electricien'
      preLoaderRoute: typeof SiteInternetElectricienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-internet-commerce': {
      id: '/site-internet-commerce'
      path: '/site-internet-commerce'
      fullPath: '/site-internet-commerce'
      preLoaderRoute: typeof SiteInternetCommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-internet-artisan': {
      id: '/site-internet-artisan'
      path: '/site-internet-artisan'
      fullPath: '/site-internet-artisan'
      preLoaderRoute: typeof SiteInternetArtisanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-visibilite': {
      id: '/seo-visibilite'
      path: '/seo-visibilite'
      fullPath: '/seo-visibilite'
      preLoaderRoute: typeof SeoVisibiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicite': {
      id: '/publicite'
      path: '/publicite'
      fullPath: '/publicite'
      preLoaderRoute: typeof PubliciteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influence-promotion': {
      id: '/influence-promotion'
      path: '/influence-promotion'
      fullPath: '/influence-promotion'
      preLoaderRoute: typeof InfluencePromotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm-automatisation': {
      id: '/crm-automatisation'
      path: '/crm-automatisation'
      fullPath: '/crm-automatisation'
      preLoaderRoute: typeof CrmAutomatisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creation-de-site': {
      id: '/creation-de-site'
      path: '/creation-de-site'
      fullPath: '/creation-de-site'
      preLoaderRoute: typeof CreationDeSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CreationDeSiteRoute: CreationDeSiteRoute,
  CrmAutomatisationRoute: CrmAutomatisationRoute,
  InfluencePromotionRoute: InfluencePromotionRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PubliciteRoute: PubliciteRoute,
  SeoVisibiliteRoute: SeoVisibiliteRoute,
  SiteInternetArtisanRoute: SiteInternetArtisanRoute,
  SiteInternetCommerceRoute: SiteInternetCommerceRoute,
  SiteInternetElectricienRoute: SiteInternetElectricienRoute,
  SiteInternetEntrepriseRoute: SiteInternetEntrepriseRoute,
  SiteInternetIrveRoute: SiteInternetIrveRoute,
  SiteInternetPhotovoltaiqueRoute: SiteInternetPhotovoltaiqueRoute,
  SiteInternetPlombierRoute: SiteInternetPlombierRoute,
  SiteInternetPmeRoute: SiteInternetPmeRoute,
  SiteInternetRestaurantRoute: SiteInternetRestaurantRoute,
  SiteInternetVtcRoute: SiteInternetVtcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
